# Configuration for ConquestHandler
# Indicate if the handler is enabled or not
enabled: ${conquest.enabled:false}
# Certificate file name. The private key alias is the filename without the extension.
certFilename: ${conquest.certFilename:conquest.jks}
# Certificate file password
certPassword: ${conquest.certPassword:password}
# Proxy Host if calling within the corp network with a gateway like Mcafee gateway.
proxyHost: ${conquest.proxyHost:}
# Proxy Port if proxy host is used. default value will be 443 which means HTTPS.
proxyPort: ${conquest.proxyPort:}
# If HTTP2 is used to connect to the conquest site.
enableHttp2: ${conquest.enableHttp2:false}

# A list of applied request path prefixes and authentication mappings, other requests will skip this handler.
# Each item will have properties to help get the token from the conquest access token service. For each API
# or request path prefix, you need to define an item in the list for authentication.
pathPrefixAuths: ${conquest.pathPrefixAuths:}
# format with JSON for config server
#  [{"pathPrefix":"/conquest","authIssuer":"Networknt","authSubject":"conquest-public-uat-networknt-jwt-integration","authAudience":"app://d5b1cb55-3835-52fc-9ef3-e38d58856396","tokenTtl":180,"tokenUrl":"https://sunlife-auth.uat.conquest-public.conquestplanning.com/login/oauth2/realms/root/realms/con/realms/uat/access_token","serviceHost":"https://conquestplanning.com"}]

# format with YAML for readability
#  - pathPrefix: /conquest
#    authIssuer: Networknt
#    authSubject: conquest-public-uat-networknt-jwt-integration
#    authAudience: app://d5b1cb55-3835-52fc-9ef3-e38d58856396
#    tokenTtl: 180
#    tokenUrl: https://sunlife-auth.uat.conquest-public.conquestplanning.com/login/oauth2/realms/root/realms/con/realms/uat/access_token
#    serviceHost: https://conquestplanning.com
