CREATE SCHEMA IF NOT EXISTS todo_db;
SET SCHEMA todo_db;
DROP table IF EXISTS TODO;
DROP table IF EXISTS message;
DROP table IF EXISTS received_messages;

CREATE TABLE TODO (
  ID varchar(255) PRIMARY KEY,
  TITLE varchar(255),
  COMPLETED BOOLEAN,
  ORDER_ID INTEGER,
  ACTIVE_FLG varchar(1) DEFAULT 'Y'
);

CREATE TABLE message (
  ID VARCHAR(120) PRIMARY KEY,
  DESTINATION VARCHAR(1000) NOT NULL,
  HEADERS VARCHAR(1000) NOT NULL,
  PAYLOAD VARCHAR(1000) NOT NULL,
  PUBLISHED INT DEFAULT 0
);

CREATE TABLE received_messages (
  CONSUMER_ID VARCHAR(120),
  MESSAGE_ID VARCHAR(120),
  PRIMARY KEY(CONSUMER_ID, MESSAGE_ID)
);

