# values.yml

# This file is a template to show how rule configurations can be injected
# per instance to override default properties in rule.yml. 
#
# The properties beneath `rule.ruleBodies` and `rule.rules` will
# be injected tightly into the runtime instances of `RuleConfig`.

# rule.ruleBodies:
#   allow-role-based-access-control.lightapi.net.dev.lightapi.net:
#     hostId: "01964b05-552a-7c4b-9184-6857e7f3dc5f"
#     ruleType: "req-acc"
#     ruleOwner: "01964b05-5532-7c79-8cde-191dcbd421b8"
#     common: "Y"
#     ruleId: "allow-role-based-access-control.lightapi.net.dev.lightapi.net"
#     ruleName: "Role-Based Access Control for authorization code token."
#     ruleVersion: "1.0.0"
#     ruleDesc: "If the token has role claim, then at least one role in the JWT role claim matches the endpoint permission roles configuration."
#     conditions:
#       - operatorCode: "isNotNull"
#         conditionId: "role-is-not-null"
#         conditionDesc: "role in the claim map is not null indicate the token has a role claim. Match it with the endpoint permission with the action."
#         propertyPath: "auditInfo.subject_claims.ClaimsMap.role"
#         index: 1
#     actions:
#       - conditionResult: false
#         actionId: "role-based-access-control-action"
#         actionDesc: "Call action to verify the role claim"
#         actionClassName: "com.networknt.rule.RoleBasedAccessControlAction"
#         actionValues:
#           - valueTypeCode: "STRING"
#             actionValueId: "permission-roles"
#             value: "$roles"

# rule.rules:
#   - endpoint: "fetch_networknt_site_docs@call"
#     apiVersion: "3.0.0"
#     endpointId: "019cb5f6-858f-7955-b9af-1c036ddaae78"
#     ruleType: "req-acc"
#     hostId: "01964b05-552a-7c4b-9184-6857e7f3dc5f"
#     ruleId: "allow-role-based-access-control.lightapi.net.dev.lightapi.net"
#     apiId: "MCP0001"
#     aggregateVersion: 1
