# Jaeger tracing implementation for the startup hook and handlers

# Indicate if the Jaeger tracing is enabled or not.
enabled: ${jaeger.enabled:false}
# Sampler configuration https://github.com/jaegertracing/jaeger-client-java
# It can either be const, probabilistic, or ratelimiting
type: ${jaeger.type:const}
# can either be an integer, a double, or an integer
param: ${jaeger.param:1}
