# request interceptor injection handler configuration

# indicator of enabled
enabled: ${request-injection.enabled:true}
# request body injection applied path prefixes. Injecting the request body and output into the audit log is very heavy operation,
# and it should only be enabled when necessary or for diagnose session to resolve issues. This list can be updated on the config
# server or local values.yml, then an API call to the config-reload endpoint to apply the changes from light-portal control pane.
# Please be aware that big request body will only log the beginning part of it in the audit log and gzip encoded request body can
# not be injected. Even the body injection is not applied, you can still transform the request for headers, query parameters, path
# parameters etc. The format is a list of strings separated with commas or a JSON list in values.yml definition from config server,
# or you can use yaml format in this file or values.yaml on local filesystem. The following are the examples.
# request-injection.appliedBodyInjectionPathPrefixes: ["/v1/cats", "/v1/dogs"]
# request-injection.appliedBodyInjectionPathPrefixes: /v1/cats, /v1/dogs
# request-injection.appliedBodyInjectionPathPrefixes:
#   - /v1/cats
#   - /v1/dogs
appliedBodyInjectionPathPrefixes: ${request-injection.appliedBodyInjectionPathPrefixes:}
# Max number of buffers for the interceptor. The default value is 1024. If the number of buffers exceeds this value, the large
# request body will be truncated. The buffer size is 16K, so the max size of the body can be intercepted is 16M. If you want to
# upload large file to the server with ExternalServiceHandler, you might need to increase the number of buffers to a larger value.
# Please be aware that the memory usage will be increased as well. So please use it with caution and test it with load test. Also,
# please make sure that you update the server.maxTransferFileSize to a larger value that matches the maxBuffers * 1024.
maxBuffers: ${request-injection.maxBuffers:1024}
