---
key:
  kid: '100'
  filename: "primary.jks"
  keyName: selfsigned
  password: password                       # private key store password and private key password is the same
issuer: urn:com:networknt:oauth2:v1
audience: urn:com.networknt
expiredInMinutes: 10
version: '1.0'
