---
# If cors handler is enabled or not
enabled: ${cors.enabled:true}

# Allowed origins, you can have multiple and with port if port is not 80 or 443
# Wildcard is not supported for security reasons.
allowedOrigins: ${cors.allowedOrigins:}
# - http://localhost

# Allowed methods list.
allowedMethods: ${cors.allowedMethods:}
# - GET
# - POST
