# LDAP server connection and search settings.
# The LDAP server uri.
uri: ${ldap.uri:}
# The LDAP domain name.
domain: ${ldap.domain:}
# The user principal for binding (authentication).
principal: ${ldap.principal:}
# The user credential (password) for binding.
credential: ${ldap.credential:}
# The search filter (e.g., (&(objectClass=user)(sAMAccountName={0}))).
searchFilter: ${ldap.searchFilter:}
# The search base DN (Distinguished Name).
searchBase: ${ldap.searchBase:}
