# Correlation Id Handler Configuration
---
# If enabled is true, the handler will be injected into the request and response chain.
enabled: true

# If set to true, it will auto-generate the correlationID if it is not provided in the request
autogenCorrelationID: true
