# Content middleware configuration.
# Indicate if the content middleware is enabled or not.
enabled: ${content.enabled:true}
# The content type to be used in the response.
contentType: ${content.contentType:application/json}
