# Server health endpoint that can output OK to indicate the server is alive

# true to enable this middleware handler.
enabled: ${health.enabled:true}

# true to return Json format message
useJson: ${health.useJson:false}